config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'users#index'

  get '/authorize', to: 'login#github_authorize'
  get '/github/callback', to: 'login#github_callback'
  post '/logout', to: 'login#logout'

  resources :users, only: %i[index] do
    resources :repositories, only: %i[index show]
    resources :projects, only: %i[index show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorize
  before_action :github_api_object, :get_user_details, if: -> { session[:access_token].present? }

  private

  def authorize
    redirect_to authorize_path if session[:access_token].nil?
  end

  def get_user_details
    @current_user = @github_api_object.get_user_details

    if @current_user.nil?
      session[:access_token] = nil
      redirect_to root_path
    end
  end

  def github_api_object
    @github_api_object ||= GithubApi.new(session[:access_token])
    if @github_api_object.nil?
      session[:access_token] = nil
      redirect_to root_path
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  skip_before_action :authorize

  def github_authorize
    @client_id = ENV['GH_BASIC_CLIENT_ID']
  end

  def github_callback
    session_code = params[:code]

    # ... and POST it back to GitHub
    result = RestClient.post('https://github.com/login/oauth/access_token',
                             { client_id: ENV['GH_BASIC_CLIENT_ID'],
                               client_secret: ENV['GH_BASIC_SECRET_ID'],
                               code: session_code },
                             accept: :json)

    if result.code == 200
      result = JSON.parse(result.body)

      unless result['error']
        # extract token and granted scopes
        p access_token = result['access_token']
        scopes = result['scope'].split(',')

        session[:access_token] = access_token
        session[:scopes] = scopes
      end
    end

    redirect_to root_path
  end

  def logout
    session[:access_token] = nil
    session[:scopes] = nil

    redirect_to root_path
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @user_projects = @github_api_object.get_projects
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController

  def index
    @user_repos = @github_api_object.get_repos
  end

  def show
    @chart_data = @github_api_object.get_repo_commits(params.require(:id))
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user_repos = @github_api_object.get_repos
    @user_projects = @github_api_object.get_projects
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GitSpectator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/login/github_authorize.html.erb
<html>
  <head>
  </head>
  <body>
    <p>
      Welcome
    </p>
    <p>
      Please Authorize through GitHub
      <a href="https://github.com/login/oauth/authorize?scope=read:user,read:org,public_repo&client_id=<%= @client_id %>">Click here</a> to begin!</a>
    </p>
  </body>
</html>

app/views/projects/index.html.erb
<div class='user-projects'>
  <% @user_projects.each do |project| %>
    <div><%= project['name']%>
  <% end %>
</div>

app/views/repositories/index.html.erb
<div class='user-repos'>
  <% @user_repos.each do |repo| %>
    <div>
      <%= link_to repo['name'], user_repository_path(id: repo['name']) %>
    </div>
  <% end %>
</div>

app/views/repositories/show.erb
<div class='repo-chart'>
  <div>
    <%= column_chart @chart_data, width: "500px", height: "300px", title: "No. of Commits" %>
  </div>
</div>

app/views/shared/_header.html.erb
<% if @current_user %>
  <div class='header'>
    <div>Hello, <%= @current_user['login'] %>!</div>
    <div>
      <%= form_with url: "/logout", method: :post do |form| %>
        <%= form.submit "Logout" %>
      <% end %>
    </div>
  </div>
  <div class='menu'>
    <%= link_to 'Home', root_path %>
    <%= link_to 'Repositories', user_repositories_path(user_id: @current_user['login']) %>
    <%= link_to 'Projects', user_projects_path(user_id: @current_user['login']) %>
  </div>
<% end %>

app/views/users/index.html.erb
<%= link_to 'View profile on GitHub', @current_user['html_url'], target: "_blank" %>